enum EntityState
{
	
	Idle				= 0,
	Victory				= 1,
	Run					= 2,
	Skid				= 3,
	Superskid			= 4,
	Fall				= 5,
	Land				= 6,
	Hover				= 7,
	Jump				= 8,
	Dash				= 9,
	CrouchJump			= 10,
	WallRun				= 11,
	WallGrab			= 12,
	WallGrabIdle		= 13,
	WallGrabRelease		= 14,
	RoofGrab			= 15,
	RoofGrabIdle		= 16,
	RoofRun				= 17,
	SlopeSlide			= 18,
	Raise				= 19,
	Stun				= 20,
	StunWall			= 21,
	StunGround			= 22,
	SlopeRun			= 23,
	Hop					= 24,
	Spawn				= 25,
	Fly					= 26,
	ThanksCleansed		= 27,
	IdleCleansed		= 28,
	IdleCleansedThanks	= 29,
	FallCleansed		= 30,
	LandCleansed		= 31,
	Cleansed			= 32,
	Block				= 33,
	WallDash			= 34,
	
}