#include '../enums/EmitterId.cpp';

namespace Emitters
{
	
	const array<int> MainEmitterIds = {
		EmitterId::DropletLong,
		EmitterId::Droplets,
		EmitterId::DustGround,
		EmitterId::Fireflies,
		EmitterId::FireflyDense,
		EmitterId::FireflySparse,
		EmitterId::KingZone,
		EmitterId::KingZoneBlue,
		EmitterId::KingZoneRed,
		EmitterId::LeafGround,
		EmitterId::PolygonsGround,
		EmitterId::Rain,
		EmitterId::SlimeGround,
		EmitterId::Sparks,
		EmitterId::TrashGround,
		EmitterId::Waterfall,
		EmitterId::WaterfallBack,
		EmitterId::WaterfallTop,
	};
	
	const array<string> MainEmitterNames = {
		'Droplet Long',
		'Droplets',
		'Dust Ground',
		'Fireflies',
		'Firefly Dense',
		'Firefly Sparse',
		'King Zone',
		'King Zone Blue',
		'King Zone Red',
		'Leaf Ground',
		'Polygons Ground',
		'Rain',
		'Slime Ground',
		'Sparks',
		'Trash Ground',
		'Waterfall',
		'Waterfall Back',
		'Waterfall Top',
	};
	
	const array<int> OtherEmitterIds = {
		EmitterId::NoName,
		EmitterId::DustRoof,
		EmitterId::DustWall,
		EmitterId::LeafRoof,
		EmitterId::LeafWall,
		EmitterId::TrashRoof,
		EmitterId::TrashWall,
		EmitterId::SlimeRoof,
		EmitterId::SlimeWall,
		EmitterId::DustGroundCreate,
		EmitterId::DustRoofCreate,
		EmitterId::DustWallCreate,
		EmitterId::LeafGroundCreate,
		EmitterId::LeafRoofCreate,
		EmitterId::LeafWallCreate,
		EmitterId::TrashGroundCreate,
		EmitterId::TrashRoofCreate,
		EmitterId::TrashWallCreate,
		EmitterId::SlimeGroundCreate,
		EmitterId::SlimeRoofCreate,
		EmitterId::SlimeWallCreate,
		EmitterId::DustGroundDestroy,
		EmitterId::DustRoofDestroy,
		EmitterId::DustWallDestroy,
		EmitterId::LeafGroundDestroy,
		EmitterId::LeafRoofDestroy,
		EmitterId::LeafWallDestroy,
		EmitterId::TrashGroundDestroy,
		EmitterId::TrashRoofDestroy,
		EmitterId::TrashWallDestroy,
		EmitterId::SlimeGroundDestroy,
		EmitterId::SlimeRoofDestroy,
		EmitterId::SlimeWallDestroy,
		EmitterId::GargoyleBig,
		EmitterId::Hit1,
		EmitterId::Maid,
		EmitterId::NoName1,
		EmitterId::Critter,
		EmitterId::Hit2,
		EmitterId::Cleansed2,
		EmitterId::Flag,
		EmitterId::Bear,
		EmitterId::Wolf,
		EmitterId::Book,
		EmitterId::Stoneboss,
		EmitterId::GargoyleSmall,
		EmitterId::Stonebro,
		EmitterId::Porcupine,
		EmitterId::PorcupineSpike,
		EmitterId::Knight,
		EmitterId::ChestScrolls,
		EmitterId::ChestTreasure,
		EmitterId::Key,
		EmitterId::Door,
		EmitterId::Scrolls,
		EmitterId::Treasure,
		EmitterId::GargoyleSmallFlap,
		EmitterId::CleansedFb2,
		EmitterId::CleansedFb1,
		EmitterId::Butler,
		EmitterId::PlygonsRoof,
		EmitterId::PolygonsWall,
		EmitterId::PolygonsGroundCreate,
		EmitterId::PlygonsRoofCreate,
		EmitterId::PolygonsGroundDestroy,
		EmitterId::PolygonsRoofDestroy,
		EmitterId::PolygonsWallDestroy,
		EmitterId::CleansedFb5,
		EmitterId::TutorialSquare,
		EmitterId::Cleansed5,
		EmitterId::TutorialHexagon,
		EmitterId::LeafDev,
		EmitterId::Apple,
		EmitterId::SlimeBall,
		EmitterId::SlimeBallFlap,
		EmitterId::Hit4,
		EmitterId::SlimeBarrel,
		EmitterId::SlimeBarrelFlap,
		EmitterId::Cleansed4,
		EmitterId::SlimeBeast,
		EmitterId::SlimWave,
		EmitterId::SlimeBarrelAttack,
		EmitterId::SlimeWave,
		EmitterId::TrashBall,
		EmitterId::TrashBallFlap,
		EmitterId::TrashCan,
		EmitterId::Hit3,
		EmitterId::Cleansed3,
		EmitterId::TrashBag,
		EmitterId::TrashBeast,
		EmitterId::TrashBeastAttack,
		EmitterId::TrashTire,
		EmitterId::CleansedFb4,
		EmitterId::NoName2,
		EmitterId::DustManTrail,
		EmitterId::DustGirlTrail,
		EmitterId::DustKidTrail,
		EmitterId::DustWorthTrail,
		EmitterId::VDustManTrail,
		EmitterId::CleansedFb3,
		EmitterId::SparksGround,
		EmitterId::SparksRoof,
		EmitterId::SparksWall,
		EmitterId::LeafSpriteTrail,
		EmitterId::DustWraithTrail,
		EmitterId::NoName3,
		EmitterId::SlimeBossTrail,
		EmitterId::TrashKingTrail,
		EmitterId::PlayerAttack2,
		EmitterId::PlayerAttackH2,
		EmitterId::PlayerAttack3,
		EmitterId::PlayerAttackH3,
	};
	
	const array<string> OtherEmitterNames = {
		'No Name',
		'Dust Roof',
		'Dust Wall',
		'Leaf Roof',
		'Leaf Wall',
		'Trash Roof',
		'Trash Wall',
		'Slime Roof',
		'Slime Wall',
		'Dust Ground Create',
		'Dust Roof Create',
		'Dust Wall Create',
		'Leaf Ground Create',
		'Leaf Roof Create',
		'Leaf Wall Create',
		'Trash Ground Create',
		'Trash Roof Create',
		'Trash Wall Create',
		'Slime Ground Create',
		'Slime Roof Create',
		'Slime Wall Create',
		'Dust Ground Destroy',
		'Dust Roof Destroy',
		'Dust Wall Destroy',
		'Leaf Ground Destroy',
		'Leaf Roof Destroy',
		'Leaf Wall Destroy',
		'Trash Ground Destroy',
		'Trash Roof Destroy',
		'Trash Wall Destroy',
		'Slime Ground Destroy',
		'Slime Roof Destroy',
		'Slime Wall Destroy',
		'Gargoyle Big',
		'Hit1',
		'Maid',
		'No Name1',
		'Critter',
		'Hit2',
		'Cleansed2',
		'Flag',
		'Bear',
		'Wolf',
		'Book',
		'Stoneboss',
		'Gargoyle Small',
		'Stonebro',
		'Porcupine',
		'Porcupine Spike',
		'Knight',
		'Chest Scrolls',
		'Chest Treasure',
		'Key',
		'Door',
		'Scrolls',
		'Treasure',
		'Gargoyle Small Flap',
		'Cleansed Fb2',
		'Cleansed Fb1',
		'Butler',
		'Plygons Roof',
		'Polygons Wall',
		'Polygons Ground Create',
		'Plygons Roof Create',
		'Polygons Ground Destroy',
		'Polygons Roof Destroy',
		'Polygons Wall Destroy',
		'Cleansed Fb5',
		'Tutorial Square',
		'Cleansed5',
		'Tutorial Hexagon',
		'Leaf Dev',
		'Apple',
		'Slime Ball',
		'Slime Ball Flap',
		'Hit4',
		'Slime Barrel',
		'Slime Barrel Flap',
		'Cleansed4',
		'Slime Beast',
		'Slim Wave',
		'Slime Barrel Attack',
		'Slime Wave',
		'Trash Ball',
		'Trash Ball Flap',
		'Trash Can',
		'Hit3',
		'Cleansed3',
		'Trash Bag',
		'Trash Beast',
		'Trash Beast Attack',
		'Trash Tire',
		'Cleansed Fb4',
		'No Name2',
		'Dust Man Trail',
		'Dust Girl Trail',
		'Dust Kid Trail',
		'Dust Worth Trail',
		'V Dust Man Trail',
		'Cleansed Fb3',
		'Sparks Ground',
		'Sparks Roof',
		'Sparks Wall',
		'Leaf Sprite Trail',
		'Dust Wraith Trail',
		'No Name3',
		'Slime Boss Trail',
		'Trash King Trail',
		'Player Attack2',
		'Player Attack H2',
		'Player Attack3',
		'Player Attack H3',
	};
	
}